### ISSUE TITLE
Does your code and data cannot be made publicly accessible?

### ISSUE THREAD

**Issue by Dinxin** [Frank-LIU-520/DeepMoleNet#1]

**Comment by Dinxin** [comment]
I think that this repo is not necessary. I don't understand why you open it.

**Comment by Frank-LIU-520** [comment]
> 
> 
> I think that this repo is not necessary. I don't understand why you open it.

Thanks for your concern about DeepMoleNet. Codes are available upon reasonable request with the correspondence address of the author. We have already made it available with the requests of researchers from several countries and regions. 
Details of our model are also shown in the paper, you are welcomed to email us with any questions.
